server: 
    port: 8881
spring:
   application:
      name: cdugga_stream_app
   kafka:
     bootstrap-servers:
     - localhost:9092s
     listener:
        log-container-config: true
     
